[tool.black]
skip-string-normalization = false
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"
force_single_line = true
line_length = 120

src_paths = ["plugins", "tests/unit"]

sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "ANSIBLE_CORE",
  "ANSIBLE_JHARMISON_CRYPTO_QOR",
  "LOCALFOLDER",
]
known_ansible_core = ["ansible"]
known_ansible_jharmison_crypto_qor = [
  "ansible_collections.jharmison.crypto_qor",
]

[tool.pytest.ini_options]
log_cli = true
